spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: zhangning1994
  mvc:
    view:
      prefix: /
      suffix: .html

server:
  port: 8080

mybatis:
  type-aliases-package: com.xcy.pojo
  mapper-locations: classpath:mapper/*.xml



