spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manl?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    password: zhangning1994
  mvc:
    view:
      prefix: /
      suffix: .html

server:
  port: 8080

mybatis:
  type-aliases-package: com.xcy.pojo
  mapper-locations: classpath:mapper/*.xml



